BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    MDTopAppBar:
        title: "Tâches"
        elevation: 4

    MDTextField:
        id: task_input
        hint_text: "Ajouter une tâche"
        pos_hint: {"center_x": 0.5}
        size_hint_x: 0.9
        mode: "rectangle"

    MDRaisedButton:
        text: "Ajouter"
        pos_hint: {"center_x": 0.5}
        on_release: app.add_task()

    ScrollView:
        MDList:
            id: task_list
